project_id = "ijhiavpjobzfxoirhnux"

[auth]
enabled = true
# Configuration for Supabase Auth

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true

[functions.process-document]
verify_jwt = false

[functions.process-appetite-document]
verify_jwt = false

[functions.auth-email]
verify_jwt = false

[functions.match-underwriters]
verify_jwt = false

[functions.intelligent-insurer-matching]
verify_jwt = false

[functions.generate-comparison]
verify_jwt = true